DROP TABLE IF EXISTS QUESTIONS;

CREATE TABLE QUESTIONS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    TOPIC VARCHAR(255) NOT NULL,
    QUESTION VARCHAR(255) NOT NULL,
    ANSWER VARCHAR(255) NOT NULL,
    BOX INTEGER NOT NULL,
    SECTION VARCHAR(255) NOT NULL,
    LASTREVIEW DATETIME
);